version: "3.4"

services:
  app:
    image: app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test-debug
    command:
      [
        "sh",
        "-c",
        "python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m pytest tests/",
      ]
    ports:
      - 8080:8080
      - 5678:5678
    env_file:
      - ../.env
  db:
    image: postgres:15.2
    env_file:
      - ../.env
    ports:
      - 5432:5432
